### ISSUE TITLE
Function analysis - Remove Range

### ISSUE THREAD

**Issue by capitanu** [SEFGroup23/assignment3-coverage#11]
Analyze the python implementation of the string strip algorithm as can be found in https://github.com/SEFGroup23/algorithms-1/blob/master/algorithms/strings/strip_url_params.py

You identify a function/method with high complexity, and document its purpose, and why the complexity should be high (or not).
You also manually count the complexity of the function (on paper or as comments).

**Comment by capitanu** [comment]
Using the tool python-radon (https://github.com/rubik/radon), the functions with worst Cyclomatic Complexity are showed. This function seemed to have a score of 18 CC, which gave a grade C (from a scale from A-F) for the function.

**Comment by ArnPellesGit** [comment]
According to Cyrille, that's a very high cyclomatic complexity: https://canvas.kth.se/courses/31884/discussion_topics/230521

**Comment by ArnPellesGit** [comment]
> Using the tool python-radon (https://github.com/rubik/radon), the functions with worst Cyclomatic Complexity are showed. This function seemed to have a score of 20 CC, which gave a grade C (from a scale from A-F) for the function.

According to Cyrille, that's a very high cyclomatic complexity: https://canvas.kth.se/courses/31884/discussion_topics/230521

**Comment by ArnPellesGit** [comment]
I ran lizard on this implementation just to see what I got as a result. The resulting cc was 10, which fits better with what Cyrille was talking about.

**Comment by capitanu** [comment]
@ArnPellesGit there's actually 3 functions in the same file. If you check the output of `lizard` you should get each one of them. The resulting 10 cc that you are getting is the average.

Here:

```
================================================
  NLOC    CCN   token  PARAM  length  location  
------------------------------------------------
      50     20    329      2      55 strip_url_params1@14-68@strip_url_params.py
       9      6    111      2      11 strip_url_params2@71-81@strip_url_params.py
       8      4     90      2      11 strip_url_params3@85-95@strip_url_params.py
1 file analyzed.
==============================================================
NLOC    Avg.NLOC  AvgCCN  Avg.token  function_cnt    file
--------------------------------------------------------------
     78      22.3    10.0      176.7         3     strip_url_params.py

=========================================================================================!!!! Warnings (cyclomatic_complexity > 15 or length > 1000 or nloc > 1000000 or parameter================================================
  NLOC    CCN   token  PARAM  length  location  
------------------------------------------------
      50     20    329      2      55 strip_url_params1@14-68@strip_url_params.py
=========================================================================================Total nloc   Avg.NLOC  AvgCCN  Avg.token   Fun Cnt  Warning cnt   Fun Rt   nloc Rt
-----------------------------------------------------------------------------------------        78      22.3    10.0      176.7        3            1      0.33    0.75
```

**Comment by capitanu** [comment]
However, I am going to change it to `linkedlist/remove_range.py`. That is, because this function already has implementations that are less complex, thus I would just redirect my solution to a different function that achieves the same thing, which is not the scope of this. 

I will modify the title of this issue.

**Comment by ArnPellesGit** [comment]
> https://github.com/SEFGroup23/algorithms-1/blob/master/algorithms/strings/strip_url_params.py

Oh now I get it. Thanks!!
